# Generated by Django 5.1.15 on 2026-08-12 19:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                (
                    "meeting_date",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("duration_seconds", models.IntegerField(default=0)),
                (
                    "participants",
                    models.JSONField(
                        default=list, help_text="List of participant names or objects"
                    ),
                ),
                ("audio_url", models.CharField(blank=True, default="", max_length=500)),
                (
                    "meeting_type",
                    models.CharField(db_index=True, default="General", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="processed",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-meeting_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-meeting_date"], name="meetings_me_meeting_b2e41a_idx"
                    ),
                    models.Index(fields=["title"], name="meetings_me_title_467a82_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("start_time", models.FloatField(default=0.0)),
                ("end_time", models.FloatField(default=0.0)),
                ("summary", models.TextField(blank=True, default="")),
                ("sequence_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_order", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ActionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task", models.TextField()),
                (
                    "assignee",
                    models.CharField(
                        blank=True, db_index=True, default="Unassigned", max_length=150
                    ),
                ),
                ("due_date", models.CharField(blank=True, default="", max_length=100)),
                ("completed", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_items",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "ordering": ["completed", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overview",
                    models.TextField(
                        help_text="High-level paragraph overview of the meeting"
                    ),
                ),
                (
                    "key_points",
                    models.JSONField(
                        default=list, help_text="List of bullet points / takeaways"
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        default=list, help_text="Extracted tags and topics"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="meetings.meeting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TranscriptSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "speaker_name",
                    models.CharField(db_index=True, default="Speaker", max_length=150),
                ),
                (
                    "speaker_avatar",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "start_time",
                    models.FloatField(
                        db_index=True,
                        default=0.0,
                        help_text="Start timestamp in seconds",
                    ),
                ),
                (
                    "end_time",
                    models.FloatField(
                        default=0.0, help_text="End timestamp in seconds"
                    ),
                ),
                ("text", models.TextField()),
                ("sequence_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript_segments",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_order", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_name", models.CharField(default="User", max_length=150)),
                ("content", models.TextField()),
                ("color_tag", models.CharField(default="yellow", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to="meetings.transcriptsegment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="transcriptsegment",
            index=models.Index(
                fields=["meeting", "sequence_order"],
                name="meetings_tr_meeting_2b0af0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transcriptsegment",
            index=models.Index(
                fields=["meeting", "start_time"], name="meetings_tr_meeting_23990d_idx"
            ),
        ),
    ]
