# Generated by Django 6.0.4 on 2026-08-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="user_email",
            field=models.CharField(
                db_index=True, default="bhawya@scaler.com", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="workspace",
            field=models.CharField(
                db_index=True, default="Scaler AI Labs", max_length=255
            ),
        ),
    ]
